apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-deploy
  namespace: dev
  labels:
    app: k8s-app-deploy
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-app-deploy
  template:
    metadata:
      labels:
        app: k8s-app-deploy
        environment: dev
    spec:
      containers:
      - name: k8s-app-deploy
        image: ghcr.io/abraham-tech/k8s-app-deploy:develop-a8b7cac
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
