apiVersion: v1
kind: Service
metadata:
  name: k8s-app-deploy-service
  namespace: prod
  labels:
    app: k8s-app-deploy
    environment: prod
spec:
  selector:
    app: k8s-app-deploy
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
